"""Setup commands: ``qa-agent init`` and ``qa-agent doctor``."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

from ._shared import console


def cmd_init(args: argparse.Namespace) -> None:
    """Interactive setup wizard — create .env and validate configuration."""
    from rich.prompt import Prompt, Confirm

    console.print("\n[bold cyan]QA Agent Ecosystem — Setup Wizard[/bold cyan]\n")

    provider = Prompt.ask(
        "Which AI provider will you use?",
        choices=["copilot", "anthropic-api", "openai", "local"],
        default="copilot",
    )

    env_lines = [
        "# QA Agent Ecosystem — generated by `qa-agent init`",
        "",
    ]

    if provider == "copilot":
        console.print("\n[dim]GitHub Copilot uses `gh auth login` for authentication.[/dim]")
        console.print("[dim]Run `gh auth login --web` if you have not authenticated yet.[/dim]\n")
        token = Prompt.ask("GITHUB_TOKEN (optional — leave blank to use gh auth)", default="")
        if token:
            env_lines.append(f"GITHUB_TOKEN={token}")
    elif provider == "anthropic-api":
        key = Prompt.ask("ANTHROPIC_API_KEY")
        env_lines.append(f"ANTHROPIC_API_KEY={key}")
    elif provider == "openai":
        key = Prompt.ask("OPENAI_API_KEY")
        env_lines.append(f"OPENAI_API_KEY={key}")
    elif provider == "local":
        console.print("[dim]Local models (Ollama/LM Studio) do not require API keys.[/dim]")

    env_path = Path(".env")
    if env_path.exists():
        overwrite = Confirm.ask(".env already exists — overwrite?", default=False)
        if not overwrite:
            console.print("[yellow]Skipped writing .env.[/yellow]")
            return

    env_path.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
    console.print(f"\n[green]✅  .env written to {env_path.resolve()}[/green]\n")
    console.print("[dim]Running doctor to validate...[/dim]\n")
    cmd_doctor(args)


def cmd_setup(args: argparse.Namespace) -> None:
    """End-to-end interactive bootstrap: deps, .env, gh auth, Playwright, doctor."""
    import shutil
    import sys
    from rich.prompt import Prompt, Confirm

    console.print("\n[bold cyan]QA Agent Ecosystem — Setup[/bold cyan]")
    console.print("[dim]Five steps: pick provider, install Python extras, configure auth, "
                  "install Playwright, run doctor.[/dim]\n")

    provider = Prompt.ask(
        "Which AI provider will you use?",
        choices=["copilot", "anthropic-api", "openai", "local", "skip"],
        default="copilot",
    )

    extras_map = {
        "copilot": "copilot",
        "anthropic-api": "anthropic",
        "openai": "openai",
        "local": "openai",
    }

    if provider != "skip":
        extra = extras_map[provider]
        if Confirm.ask(f"\nInstall Python extras for `{extra}` (pip install -e \".[{extra}]\")?", default=True):
            console.print(f"[dim]→ pip install -e \".[{extra}]\"[/dim]")
            r = subprocess.run([sys.executable, "-m", "pip", "install", "-e", f".[{extra}]"])
            if r.returncode != 0:
                console.print("[red]pip install failed — fix the error above and re-run setup.[/red]")
                return

    if provider == "anthropic-api" and shutil.which("anthropic") is None:
        if Confirm.ask("Also install the `anthropic` SDK?", default=True):
            subprocess.run([sys.executable, "-m", "pip", "install", "anthropic"])

    env_path = Path(".env")
    write_env = True
    if env_path.exists():
        write_env = Confirm.ask(f"\n.env already exists at {env_path.resolve()} — overwrite?", default=False)

    if write_env:
        env_lines = ["# QA Agent Ecosystem — generated by `qa-agent setup`", ""]
        if provider == "copilot":
            console.print("\n[dim]Copilot uses `gh auth login`. You can leave GITHUB_TOKEN blank.[/dim]")
            token = Prompt.ask("GITHUB_TOKEN (optional)", default="", show_default=False)
            if token:
                env_lines.append(f"GITHUB_TOKEN={token}")
        elif provider == "anthropic-api":
            key = Prompt.ask("ANTHROPIC_API_KEY", password=True)
            env_lines.append(f"ANTHROPIC_API_KEY={key}")
        elif provider == "openai":
            key = Prompt.ask("OPENAI_API_KEY", password=True)
            env_lines.append(f"OPENAI_API_KEY={key}")
        elif provider == "local":
            console.print("[dim]Local models do not require API keys.[/dim]")
        env_path.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
        console.print(f"[green].env written to {env_path.resolve()}[/green]")

    if provider == "copilot":
        gh_ok = False
        if shutil.which("gh"):
            r = subprocess.run(["gh", "auth", "status"], capture_output=True, text=True)
            gh_ok = r.returncode == 0
        if not gh_ok:
            if Confirm.ask("\nRun `gh auth login --web` now?", default=True):
                if shutil.which("gh") is None:
                    console.print("[red]GitHub CLI (`gh`) is not installed. Install from https://cli.github.com and re-run setup.[/red]")
                else:
                    subprocess.run(["gh", "auth", "login", "--web"])
        else:
            console.print("[green]GitHub CLI is already authenticated.[/green]")

        console.print(
            "\n[bold red on white] !!! IF COPILOT STOPS WORKING !!! [/bold red on white]\n"
            "[bold red]If the app can't reach GitHub Copilot, re-run:[/bold red]\n"
            "[bold yellow]    gh auth refresh --scopes copilot[/bold yellow]\n"
        )

    pw_dir = Path("playwright")
    if pw_dir.is_dir() and Confirm.ask("\nInstall Playwright (`npm install` + `npx playwright install --with-deps`)?", default=True):
        npm = shutil.which("npm") or "npm"
        npx = shutil.which("npx") or "npx"
        if shutil.which("npm") is None:
            console.print("[red]npm not found. Install Node.js 18+ from https://nodejs.org and re-run setup.[/red]")
        else:
            subprocess.run([npm, "install"], cwd=str(pw_dir))
            subprocess.run([npx, "playwright", "install", "--with-deps"], cwd=str(pw_dir))

    console.print("\n[bold]Running doctor…[/bold]")
    cmd_doctor(args)


def cmd_doctor(_args: argparse.Namespace) -> None:
    """Validate configuration, API keys, gh auth, and Playwright."""
    checks: list[tuple[str, bool, str]] = []

    env_exists = Path(".env").exists()
    checks.append((".env file present", env_exists, "Run `qa-agent init` or copy .env.example to .env"))

    try:
        from qa_ecosystem.models import resolve_model
        profile = resolve_model()
        key_ok = profile.resolve_api_key() is not None
        checks.append((
            f"API key for default profile ({profile.name})",
            key_ok,
            "Set the required env var (e.g. ANTHROPIC_API_KEY) in your .env file",
        ))
    except Exception as exc:
        checks.append(("Default model profile resolves", False, str(exc)))

    try:
        result = subprocess.run(
            ["gh", "auth", "status"],
            capture_output=True, text=True, timeout=10
        )
        gh_ok = result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        gh_ok = False
    checks.append(("GitHub CLI authenticated (gh auth status)", gh_ok,
                   "Run `gh auth login --web` to authenticate"))

    try:
        import shutil
        npx = shutil.which("npx") or "npx"
        result = subprocess.run(
            [npx, "playwright", "--version"],
            capture_output=True, text=True, timeout=15, cwd="playwright"
        )
        pw_ok = result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        pw_ok = False
    checks.append(("Playwright installed (npx playwright)", pw_ok,
                   "Run `cd playwright && npm install && npx playwright install --with-deps`"))

    try:
        from qa_ecosystem.models import list_profiles
        profiles = list_profiles()
        yaml_ok = len(profiles) >= 1
    except Exception:
        yaml_ok = False
    checks.append(("models.yaml valid and has profiles", yaml_ok,
                   "Check qa_ecosystem/models.yaml for YAML syntax errors"))

    console.print("\n[bold]QA Agent Ecosystem — Doctor[/bold]\n")
    all_ok = True
    for label, ok, fix in checks:
        icon = "[green]✅[/green]" if ok else "[red]❌[/red]"
        console.print(f"  {icon}  {label}")
        if not ok:
            console.print(f"     [dim]→ {fix}[/dim]")
            all_ok = False

    console.print()
    if all_ok:
        console.print("[bold green]All checks passed — you're ready to go![/bold green]\n")
    else:
        console.print("[bold yellow]Some checks failed. See hints above.[/bold yellow]\n")


def register(sub) -> None:
    sub.add_parser("setup", help="One-shot interactive bootstrap (deps, .env, gh auth, Playwright, doctor)")
    sub.add_parser("init", help="Create or refresh .env only (no installs)")
    sub.add_parser("doctor", help="Validate configuration, API keys, gh auth, and Playwright")


COMMANDS = {
    "setup": cmd_setup,
    "init": cmd_init,
    "doctor": cmd_doctor,
}
